### ISSUE TITLE
Add instructions for how SAVINGS are allocated

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Ops#27]
Currently the [Savings](https://docs.dorg.tech/how-dorg-works/value-flow) page shows how savings accumulate but not how we struture decisions around spending them.

I think this is also an opportunity to develop a more robust process for this..

**Comment by orishim** [comment]
One way we could go about this is through making DAO proposals to merge "dOrg Spending Proposals" (DSPs) to this repo here:
https://github.com/dOrgTech/Ops/blob/master/proposals/_dsp-template.md

We also need a way to more transparently track dOrg's available savings for these projects.

**Comment by magentaceiba** [comment]
Toward removing the Budget Blocks Airtable, I've created an interim spreadsheet for review. (Next goal is to create this sheet as a tab within Nucleus, with formulas to automate it)
https://docs.google.com/spreadsheets/d/16a4tINSZaZHKLa3VizqiLL1Gp6wREP0GJ6QPf4q7xO4/edit?usp=sharing

--In this sheet I made a box that's intended to display the snapshot of our reserves and runway, for people to reference when voting on DSP's.
--Questions highlighted in blue.
--Additional question: Where should we display internal ops distributions if we're getting rid of budget blocks? 

Once this is reviewed, I have a process written up to add to the Handbook's savings page, for builders to submit and vote on DSP's. It includes where to look to see our current reserves and how the DSP would impact our runway, etc.

**Comment by orishim** [comment]
Looks great!

There is no longer an internal ops budget with this system. That's why we passed the DSP specifically to fund admin, facilitation, and comms work over this next 9 week period. This means that  we don't really need blocks/snapshots or runway calculations. It can just be a running total of our current reserve based on the margin on client projects minus any spending from DSPs.

**Comment by magentaceiba** [comment]
The dOrg Balance Sheet looks great. Even though it’s still a manual process, it seems ready to add as a last tab on Nucleus. Sound good?
