### ISSUE TITLE
 List the roles that dOrg is currently hiring for

### ISSUE THREAD

**Issue by rihp** [dOrgTech/Ops#29]
- [ ] Review current roles in the organization
- [ ] ....

**Comment by orishim** [comment]
- Smart Contract Engineer (Solidity)
- Web3 Integrations Engineer (React, Redux, ethers.js, web3.js)
- UX/UI Designer (Figma)

**Comment by rihp** [comment]
Since this is recurring, idk if we should be closing/reopening the issue, or creating the issue each month

**Comment by orishim** [comment]
I like just making this a part of the recurring task to tweet when new builders join (#31 ). We will also have "Open Positions" as part of the website redesign.
