### ISSUE TITLE
Establish culture of asking for help early

### ISSUE THREAD

**Issue by rihp** [dOrgTech/Ops#34]

**Comment by orishim** [comment]
We mention asking your fellow builders for help in this page of the handbook:
https://docs.dorg.tech/workflows/executing

We also added "Quality Assurance" to the facilitation role, which means that person will reach out to check if teams are experiencing any problems.

@rihp do you have other ideas for instituting this culture?

**Comment by orishim** [comment]
I definitely like the idea of building this into the biweekly sync agendas. Something like this:

- (20 min) Updates and new builder intros
- (60 min) Agenda items 
- (10 min) "Help desk" open time for troubleshooting any builder problems

**Comment by rihp** [comment]
The timed intro/outro definitely sounds like a good approach for the syncs, which right now are a more improvised.

The help desk could be good, but probably 10 minutes wont be enough to cover all inquiries, and they could get too specific for a group-wide meeting. 

I'd still consider scheduling a short time aside during kick offs, to reinforce awareness of those values we all consider are important for the group. Does it maybe sounds a bit too cheesy?

**Comment by orishim** [comment]
Ah yes, having a structured agenda for the project kickoff call which includes a reinforcement of this point also sounds like a good idea.

**Comment by orishim** [comment]
added to structured agenda, we have also made the coordinator role more robust in identifying and addressing problems early on
