### ISSUE TITLE
Landing Page Redesign

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Ops#37]
I've suggested a new structure for our landing page here: https://docs.google.com/presentation/d/1P7jeGETFRJBKlyXUjk9j9-QUUa8BctjFVSwMaIyev6M

I think we should contract 99designs to get this design to completion and implement it with a website builder.

We'd need to decide on a budget (I think $2-3k would be enough) and make a dOrg Spending Proposal.

**Comment by rihp** [comment]
Look at the landingpage brief in 99designs created by Ori
- [ ] Define budget 
- [ ] End date
- [ ]

**Comment by rihp** [comment]
Contest was submitted yesterday to 99designs

PR with more details:
https://github.com/dOrgTech/Ops/pull/61/files?short_path=66fef1a#diff-66fef1a4cde9c4c80154287a73c51e2e3bab381cb0a0f76f5d5c910825821cad

**Comment by rihp** [comment]
Resulting design is being handed over to @benefacto for in-house implementation!
