### ISSUE TITLE
DAO Partnerships strategy

### ISSUE THREAD

**Issue by rihp** [dOrgTech/Ops#52]

**Comment by rihp** [comment]
Thinking of automating this as much as possible.

What do you think are key categories or channel to sort communication?

For example, filtering a list of DAO broadcasts by these categories:
- Hiring
- For Hire
- Feedback

**Comment by rihp** [comment]
This can be an streamlined process which takes all the broadcasted DAO posts and automatically tweets them.

**Comment by rihp** [comment]
Consider repurposing this infrastructure by @LPSCRYPT
https://github.com/LPSCRYPT/dpost-alpha

**Comment by rihp** [comment]
Requests partner DAOs to create their own `org.json`files:  
https://docs.dorg.tech/governance/global-variables

**Comment by rihp** [comment]
Once we get a few communities onboard with this initiative, we should create a blog post to promote the adoption of standard across the ecosystem. 

A DAO Alliance sync call is scheduled for Tomorrow Wednesday 12pm PST, where several DAO leads will attend

**Comment by rihp** [comment]
focus first on a one-to-many communication strategy for dOrg.

**Comment by rihp** [comment]
Consider using airtable to track these relationships
add more entities (aragon, daostack, etc)
schedule meetings at least once a month 


https://airtable.com/tblZc3HquQ9JWZ5BI/viwJrsSAXtRxWrZLN?blocks=hide

**Comment by orishim** [comment]
We could make an "Ecosystem Partners" google calendar that contains Dxdao, Prime, and other's weekly calls.

**Comment by orishim** [comment]
Not sure we've made any progress here
