### ISSUE TITLE
Calendar for community calls

### ISSUE THREAD

**Issue by rihp** [dOrgTech/Ops#55]
List all of the other DAO's community calls and have a representative there

**Comment by rihp** [comment]
Prime DAO
- Bi-monthly, Tuesdays, 17:30 UTC
- ZOOM LINK: https://zoom.us/j/3957392602

Badger DAO
-
-

Aragon 
-
-

DAOstack
-
-

**Comment by rihp** [comment]
- [ ] List these On the team calendar with GSuite

**Comment by orishim** [comment]
Let's make it a separate calendar called "Ecosystem Partners" or similar

**Comment by orishim** [comment]
Done
