### ISSUE TITLE
Zoho -> G Suite

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Ops#60]

**Comment by rihp** [comment]
🙏

**Comment by magentaceiba** [comment]
- [ ] Open a plan on the Business Starter level

- [ ] Create multiple admins

- [ ] Migrate emails and make sure let everyone know when that's going to happen

- [ ] Post instructions to help people with export their emails from Zoho before we close the account https://www.systoolsgroup.com/import/zoho-to-g-suite-migration/

- [ ] Start file tree for consistent formatting

**Comment by orishim** [comment]
- [x] deprecate zoho budget spreadsheet and move it to google sheets ([see here](https://docs.google.com/spreadsheets/d/1mwYhzTNXSytzVtACZLu1V_EVTfjPKhGfHu-KhnBFESk/))
- [x] replace info about zoho in [onboarding docs](https://docs.dorg.tech/lifecycle/onboarding) with google
