### ISSUE TITLE
Frontend Developer

### ISSUE THREAD

**Issue by rihp** [dOrgTech/Ops#79]
# Wanted: Frontend Developer
> Remote, Engineering, Full-Time

[dOrg](https://dOrg.tech) is seeking highly skilled and experienced developers to contribute building dApps, prototypes, and experiences.

## About dOrg

We are a full-stack Web3 development collective. 

## Role Description

**Responsibilities:**

- Work on mission-critical client projects with limited/no supervision
- Play an active role in the design and architecture of client products
- Help improve the dOrg organization and DAO experience

**Skills & Qualifications:**

- A passion for...
    - Decentralization, Cryptocurrency, Web3, Blockchain, DAOs, DeFi
- Experience using some of these...
    - TypeScript / JavaScript
    - React, Angular, Vue
    - Web3.js, ethers.js
    - Redux / Hooks
    - Bonus: Blockchain, P2P Technologies, Solidity, Python, Rust
- Demonstrated ability to...
    - Learn new technology quickly
    - Write secure and high quality code
    - Publish & maintain production grade software

**Benefits**  
- Work on interesting projects 🛠 with talented peers 🥇 anytime, anywhere 🏖
- Earn income 💸 for building, commissions 📊 for sourcing, and airdrops ☔️ whenever we ship
- Enjoy perks like discounted tax prep 📂 shared subscriptions 📡 swag 🧢 and more! 
- Leverage shared resourced to launch 🚀 your own projects

**Commitment Level**  
- Full-Time (Ideal)  
- Part-Time (Minimum)  

**Compensation**
- Payment will be commensurate with experience level and client project budgets.

### To apply for this position, please fill out this [form](https://airtable.com/shrwqFWKvcWunpsMw)

**Comment by orishim** [comment]
**Benefits**
- Work on *challenging problems* 🛠 with *great people* 🥇
- *Freedom* 🦅 - Work wherever, whenever
- *Unlimited Upside* 💸- Earn based on the value you generate, not predetermined salaries 
- *Regular Airdrops* ☔️ - The more you earn, the larger share you get of client token airdrops
- *Commissions* 📊- Get rewarded for referring other builders and sourcing new project
- *Project Launchpad* 🚀 - Leverage shared resources to launch your own projects 
- *Group Benefits* 🎡 - Enjoy discounted personal tax prep, shared newsletter subscriptions, qualified expense reimbursements, and more!
