### ISSUE TITLE
Revamp proposal template

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Ops#80]
Fork our [current proposal template](https://docs.google.com/document/d/17Yf2pXQVWgmmVvvDyG_q7tB2we9nyzeZJpE8PkoFqI8/edit?usp=sharing) or create a new one from scratch with the following improvements:
- *Internal Review Practices*
  - Describe our quality standards, how internal review works, expectations around audits
  - Add specific line item (e.g. 8 hrs of internal review by veteran builders)
- *Execution Lead Role*
  - Describe the role's purpose: facilitating communications, meeting deadlines, monitoring scope, rotating builders, evaluating risk
  - Instruct client to interface through them
  - Add specific line item (e.g. 8 hrs / wk of execution )
- *Flexible Roadmap*
  - Explain that the roadmap is an estimate based on current scope of work that does not account for unexpected delays, changes in scope, or additional work.
  - Add in a default buffer of potential delay (1 week for every 4 weeks)
- *Recurring Billing*
  - Instructions on how to pay with ETH or stable coins with [Request Network](https://request.network/en/)
  - Terms about late payments
- *Rep-Holder Airdrop*
  - Instructions for clients also paying in native tokens 
- *Feedback Processes*
  - Build in some sort of regular feedback..
  - Short form that the client fills out with each bill + longer form at project completion
  - Mirror this with builder feedback that we share with the client?

@rihp @jessebmiller @Remscar @benefacto @magentaceiba @PhilH @dOrgJelli @xiphiness @namesty @cbrzn @shresthagrawal @DavidWolff218

**Comment by benefacto** [comment]
[This proposal](https://docs.google.com/document/d/1-nAlBo8f15_Xl2DHfcO0IHTiDmnzpQ3tT4IMYPo0XaY/edit?usp=sharing) was an example of my latest attempt at addressing some of these concerns but I think a lot more could be done on this.

**Comment by orishim** [comment]
Also consider including some metadata outside of the client-facing proposal for dOrg builders to evaluate, such as a:
- Impact Score
- Difficulty/Risk Score

Credit to Jessica for these! ^

**Comment by orishim** [comment]
This new proposal template could also encompass some of the details currently contained in the SoW template, so that we can eliminate that step from the sourcing process

**Comment by orishim** [comment]
https://hackmd.io/QlAkoWTZSH-hRiN1MyoJtw

**Comment by orishim** [comment]
Posted the new template in pinned message here: 
https://discord.com/channels/544647726982365194/803414289704157214/807003636957577297
