### ISSUE TITLE
Add 'Code of Ethics'

### ISSUE THREAD

**Issue by orishim** [dOrgTech/Ops#9]
Expectations around..
- personally taking equity, tokens, or titles in the client
- going to work for the client without dOrg

**Comment by PhilH** [comment]
dOrg being an open collective, I think that members should be and feel free to join projects they engage with as dOrg independent workers.

However, it would be fair to have clients rewarding dOrg with a finder's fee if they end up hiring a dOrg member. It's only fair to have the client paying for what is essentially a recruitment service. It can be phrased as a non-solicitation clause that can be waived provided that a set fee is paid by the client to dOrg. 20% of the annual salary is common.

**Comment by orishim** [comment]
Add a section on the Code of Ethics page about "Public Conduct". Members who publicly associate themselves with dOrg should follow some basic minimum standard of conduct like avoiding promotion of violence, racism, sexism, excessive profanity, etc.
